# 데이터 핸들링을 위한 라이브러리 NumPy

## 1. Numpy
Numerical Python  
Python에서 대규모 다차원 배열을 다룰 수 있게 도와주는 라이브러리  

데이터의 대부분은 숫자 배열로 볼 수 있는데, numpy를 이용하면 반복문 없이 배열 처리를 할 수 있어 빠른 연산과 효율적인 메모리 사용이 가능하다.

In [3]:
list_arr = list(range(5))
print(list_arr)
print(type(list_arr))

[0, 1, 2, 3, 4]
<class 'list'>


In [4]:
import numpy as np

In [5]:
import numpy as np
np_arr = np.array(range(5))
print(np_arr)
print(type(np_arr))

[0 1 2 3 4]
<class 'numpy.ndarray'>


- ndarray : n차원의 배열 (n-dimensional array)

### 1.1 실습 - 배열 만들기
0부터 4까지 연속적인 숫자가 들어있는 배열을 만들어 array라는 배열에 저장해봅시다!

In [23]:
import numpy as np

# 0부터 4까지 연속적인 숫자가 들어있는 배열을 만들어 봅시다!
array = np.array(range(5))
print(array)

[0 1 2 3 4]


## 2. 배열의 기초
리스트와 달리 같은 데이터 타입만 저장 가능  
(리스트와 다른 것!!!)  

In [6]:
arr = np.array([0,1,2,3,4],dtype = float)
print(arr)
print(arr.dtype)
print(arr.astype(int))

[0. 1. 2. 3. 4.]
float64
[0 1 2 3 4]


In [7]:
list = [0,1,2,3]
arr = np.array(list)
print(arr.ndim)
print(arr.shape)

1
(4,)


In [8]:
list = [[0,1,2],[3,4,5]]
arr = np.array(list)
print(arr.ndim)
print(arr.shape)

2
(2, 3)


- ndim : 
- shape : 

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5])
print("arr.shape : {}".format(arr.shape)) 
print("배열 요소의 수 : {}".format(arr.size)) 
print("배열의 길이 : {}".format(len(arr)))

arr.shape : (6,)
배열 요소의 수 : 6
배열의 길이 : 6


In [10]:
arr.shape = 3, 2
print("arr.shape : {}".format(arr.shape)) 
print("배열 요소의 수 : {}".format(arr.size)) 
print("배열의 길이 : {}".format(len(arr)))

arr.shape : (3, 2)
배열 요소의 수 : 6
배열의 길이 : 3


### 2.1 실습 - 배열의 기초
1. array의 자료형을 출력해보세요. type() 함수로 변수의 자료형을 구할 수 있습니다.  
이 type(array)의 의미는 array라는 변수가 파이썬에서 어떤 자료형으로 저장되고 있는지 알 수 있는 것입니다.
2. array의 차원을 출력해보세요.
3. array의 모양을 출력해보세요.
4. array의 크기를 출력해보세요.
5. array의 dtype을 출력해보세요. dtype이란, numpy 배열이 갖고 있는 요소의 자료형을 의미합니다.
6. array의 인덱스 5의 요소를 출력해보세요.
7. array의 인덱스 3의 요소부터 인덱스 5의 요소까지 출력해보세요.

In [25]:
import numpy as np

print("1차원 array")
array = np.array(range(10))
print(array)

# 1. array의 자료형을 출력해보세요.
print(type(array))

# 2. array의 차원을 출력해보세요.
print(array.ndim)

# 3. array의 모양을 출력해보세요.
print(array.shape)

# 4. array의 크기를 출력해보세요.
print(array.size)

# 5. array의 dtype(data type)을 출력해보세요.
print(array.dtype)

# 6. array의 인덱스 5의 요소를 출력해보세요.
print(array[5])

# 7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해보세요.
print(array[3:6])


1차원 array
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int32
5
[3 4 5]


### 2.2 실습 - 배열의 기초
1. matrix의 자료형을 출력해보세요. type(matrix)로 자료형을 구할 수 있습니다.
2. matrix의 차원을 출력해보세요.
3. matrix의 모양을 출력해보세요.
4. matrix의 크기를 출력해보세요.
5. matrix의 dtype을 출력해보세요.
6. matrix의 dtype을 str로 변경하여 출력해보세요.
7. matrix의 인덱스 (2,3)번째 요소를 출력해보세요.
8. matrix의 인덱스 (0,1)번째 요소부터 (1,3)번째 요소까지 출력해보세요.

In [26]:
import numpy as np

print("2차원 array")
#1부터 15까지 들어있는 (3,5)짜리 배열을 만듭니다.
matrix = np.array(range(1,16))
matrix.shape = 3,5
print(matrix)


# 1. matrix의 자료형을 출력해보세요.
print(type(matrix))

# 2. matrix의 차원을 출력해보세요.
print(matrix.ndim)

# 3. matrix의 모양을 출력해보세요.
print(matrix.shape)

# 4. matrix의 크기를 출력해보세요.
print(matrix.size)

# 5. matrix의 dtype(data type)을 출력해보세요.
print(matrix.dtype)

# 6. matrix의 dtype을 str로 변경하여 출력해보세요.
print(matrix.astype(str))

# 7. matrix의 (2,3) 인덱스의 요소를 출력해보세요.
print(matrix[2,3])
#print(matrix[2][3])

# 8. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해보세요.
print(matrix[0:2,1:4])
#print(matrix[0:2][1:4])

2차원 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int32
[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']
 ['11' '12' '13' '14' '15']]
14
[[2 3 4]
 [7 8 9]]


## 3. Indexing & Slicing
Indexing : 인덱스로 값을 찾아냄  
Slicing : 인덱스의 값으로 배열의 일부분을 가져옴  

In [12]:
x = np.arange(7)
print(x) 
print(x[3]) 
#  print(x[7]) -> IndexError: index 7 is out of bound
x[0] = 10
print(x)

[0 1 2 3 4 5 6]
3
[10  1  2  3  4  5  6]


In [13]:
x = np.arange(1, 13 ,1)
x.shape = 3, 4
print(x) 
print(x[2, 3]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12


In [14]:
x = np.arange(7)
print(x) 
print(x[1:4]) 
print(x[1:]) 
print(x[:4]) 
print(x[::2])

[0 1 2 3 4 5 6]
[1 2 3]
[1 2 3 4 5 6]
[0 1 2 3]
[0 2 4 6]


In [15]:
x = np.arange(1, 13 ,1)
x.shape = 3, 4
print(x) 
print(x[1:2,:2:3]) 
print(x[1:,:2]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5]]
[[ 5  6]
 [ 9 10]]


### Boolean indexing
Boolean indexing : 배열의 각 요소의 선택 여부를 Boolean mask를 이용하여 지정하는 방식  
Boolean mask : True, False로 구성된 mask array  

Boolean mask의 True 요소에 해당하는 index만을 조회하는 방식으로 응용이 가능하다.

In [16]:
x = np.arange(7)
print(x)
print(x < 3) 
print(x > 7) 

[0 1 2 3 4 5 6]
[ True  True  True False False False False]
[False False False False False False False]


In [17]:
x = np.arange(7)
print(x[x < 3]) 
print(x[x % 2 == 0]) 

[0 1 2]
[0 2 4 6]


### Fancy indexing
Fancy indexing : 배열의 각 요소 선택을 index 배열을 전달하여 지정하는 방식

In [18]:
x = np.arange(7)
print(x) 
print(x[[1, 3, 5]]) 

[0 1 2 3 4 5 6]
[1 3 5]


In [19]:
x = np.arange(1, 13 ,1).reshape(3, 4)
print(x) 
print(x[[0, 2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


원하는 결과를 내기 위해 indexing과 slicing을 적절히 조합하여 사용하면 된다.

In [20]:
x = np.arange(1, 13 ,1).reshape(3, 4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(x[1:2, 2]) 
print(x[[0,2], 2])
print(x[[0,2], :2])

[7]
[ 3 11]
[[ 1  2]
 [ 9 10]]


### 실습 - Indexing & Slicing

1. Indexing을 통해 값 2를 answer1에 저장해보세요.
2. Slicing을 통해 매트릭스 일부인 9, 10을 가져와 answer2에 저장해보세요.
3. Boolean indexing을 통해 5보다 작은 수를 찾아 answer3에 저장해보세요.
4. Fancy indexing을 통해 두 번째 행만 추출하여 answer4에 저장해보세요.

In [27]:
import numpy as np

matrix = np.arange(1, 13, 1).reshape(3, 4)
print(matrix)

# 1. Indexing을 통해 값 2를 출력해보세요.
answer1 = matrix[0,1]

# 2. Slicing을 통해 매트릭스 일부인 9, 10을 가져와 출력해보세요.
answer2 = matrix[2:,:2]

# 3. Boolean indexing을 통해 5보다 작은 수를 찾아 출력해보세요.
answer3 = matrix[matrix < 5]

# 4. Fancy indexing을 통해 두 번째 행만 추출하여 출력해보세요.
answer4 = matrix[[1]]

# 위에서 구한 정답을 출력해봅시다.
print(answer1)
print(answer2)
print(answer3)
print(answer4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 9 10]]
[1 2 3 4]
[[5 6 7 8]]
